### ISSUE TITLE
Allow Title Color

### ISSUE THREAD

**Issue by adrianvintu** [Arbaz-Softagics/commons#2]
Thank you for your amazing work!

Can you please allow for us to change the background color of the round circle in the `infoDialog` et co?

I am talking about this  `__AlertDialog.INFO` <- it's const and hidden :(

**Comment by Arbaz-Softagics** [comment]
Thanks for your concern. 
i will make this dynamic, you can use this on the next version soon.

**Comment by adrianvintu** [comment]
@Arbaz-Softagics thank you very much!

**Comment by Arbaz-Softagics** [comment]
Version **0.6.5** available now you can use this function for change color and icon as your choice.

`dialog(context, Colors.pink, "Title", "Some message", false, true, customIcon: Icon(Icons.ac_unit, size: 64, color: Colors.white,),);`

**Comment by adrianvintu** [comment]
Thank you @Arbaz-Softagics
