### ISSUE TITLE
Background color depending on Theme

### ISSUE THREAD

**Issue by adrianvintu** [Arbaz-Softagics/commons#3]
Can you please make the background of the dialog configurable, or something like that?

For now, it is not respecting custom dark theme, it shows the background as white, no matter what theme is set.

**Comment by Arbaz-Softagics** [comment]
Theme support is already in my pending list. You will get that soon.

**Comment by adrianvintu** [comment]
Thank you, keep up the great work!

**Comment by Arbaz-Softagics** [comment]
Commons 0.6.9 available for theme support. Hope it helps.

**Comment by adrianvintu** [comment]
@Arbaz-Softagics thank you, here are some notes:
on BLACK theme
1. OK button color is not accent color
2. icon "i" has WHITE round **skinny** circle, instead of possibly TEXT color? or maybe it looks better in white?
3. icon "i" has WHITE font, instead of possibly TEXT color? or maybe it looks better in white?

on WHITE theme:
looks as previous, i.e. good.


Tested with:
```
    dialog(
      context,
      //Theme.of(context).accentColor,
      widget.highlightBackgroundColor,
      "",
      text,
      true,
      true,
      neutralText: "Ok",
      neutralAction: () {},
      customIcon: Icon(
        Icons.info_outline,
        size: 64,
        color: Colors.white,
      ),
    );
```

**Comment by Arbaz-Softagics** [comment]
Commons v 0.7.0 is available with new changes
1 - Button colors changed to accent color
2, 3 - Icon color looks batter in white.
