### ISSUE TITLE
Default check is not enabled for single selection dialog!

### ISSUE THREAD

**Issue by MuthuSubramaniam** [Arbaz-Softagics/commons#7]
It's a great work, and much appreciate if you guys gets attention on this issue.
As per my knowledge, I am trying to open a dialog with single selection radio button. 

This is how i added 
![image](https://user-images.githubusercontent.com/39517706/78846744-5cff8780-7a3f-11ea-8ad5-9509be407166.png)

isSelected parameter seems not been used in your code!

![image](https://user-images.githubusercontent.com/39517706/78846634-f7130000-7a3e-11ea-9bc0-abf18c14f9ea.png)

**Comment by Arbaz-Softagics** [comment]
selected value used only for multi selection list items. See [Multi Select Example](https://github.com/Arbaz-Softagics/commons/tree/master/example) for selected item on dialogs.
